### ISSUE TITLE
Bootcamp pre-work: Todo App ready for review

### ISSUE THREAD

**Issue by sushmatn** [sushmatn/TodoApp#1]
My Todo app with the suggested extensions is ready for review.  /cc @codepathreview @codepath

**Comment by sushmatn** [comment]
Added an option to set the due date and time.
Added the ability to get notifications on the due date when a reminder is set.

Ready for review.  /cc @codepathreview @codepath

**Comment by nidhi1608** [comment]
Excellent work Sushma. This exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.

The next step is to <b>schedule a short 5-10 minute phone conversation</b> [here](https://www.google.com/calendar/selfsched?sstoken=UU5IOEduOWEtRDg5fGRlZmF1bHR8NWRiNTI5ZWJmMjVjODg1OGVhMmU0NDg5Nzc2NDRlNTc). Navigate to [today's date and onward from there](https://www.google.com/calendar/selfsched?sstoken=UU5IOEduOWEtRDg5fGRlZmF1bHR8NWRiNTI5ZWJmMjVjODg1OGVhMmU0NDg5Nzc2NDRlNTc) and choose a 15-minute slot. Let us know if none of those times work.

Once you select a slot, can you make sure to include best number to reach you at to the invite? Look forward to chatting soon!

**Comment by sushmatn** [comment]
Added the following extensions:
- Added an option to accept microphone input for entering task title and task details.
- The user can swipe to delete a task.

Ready for review. /cc @codepathreview @codepath

**Comment by nidhi1608** [comment]
Looks good Sushma. We'll get in touch with you via email in the next few days.
